# -*- coding: utf-8 -*-
"""VOICE ASSISTANT PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JshxjfYkNliC1xZB4--EcaGFT0zQHb5z
"""

!pip install SpeechRecognition gTTS

import speech_recognition as sr
from gtts import gTTS
from IPython.display import Audio, display
import os

from google.colab import files

# Upload your audio file
uploaded = files.upload()

# Save the file name
audio_file = list(uploaded.keys())[0]

# Initialize recognizer
recognizer = sr.Recognizer()

# Process the audio file
with sr.AudioFile(audio_file) as source:
    audio_data = recognizer.record(source)

# Recognize speech using Google Web Speech API
try:
    text = recognizer.recognize_google(audio_data)
    print("Recognized Text:", text)
except sr.UnknownValueError:
    print("Could not understand the audio")
except sr.RequestError as e:
    print(f"Error with SpeechRecognition service: {e}")

# Text to Speech
if 'text' in locals():  # Check if transcription was successful
    tts = gTTS(text, lang='en')
    tts.save("response.mp3")
    print("Generated Voice Response:")
    display(Audio("response.mp3", autoplay=True))
else:
    print("No text available to convert to speech.")